---
- hosts: localhost
  become: yes

  tasks:

    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Create web page
      copy:
        content: "<h1>Update by automation test demo n22dccn168 final manhsangdv</h1>"
        dest: /var/www/html/index.html
